---
- name: Check folder
  stat:
    path: '{{ remote_working_directory }}/backend/backend/config/'
  register: backend_conf_dir

- name: Create directory
  file:
    path: '{{ remote_working_directory }}/backend/backend/config/'
    recurse: yes
    state: directory
  when: backend_conf_dir.stat.exists == false

- name: generate backend configuration for couchdb
  template:
    src: backend-couchdb-config.py.j2
    dest: '{{ remote_working_directory }}/backend/backend/config/config.py'
    owner: ubuntu
    group: ubuntu
    force: no

- name: copy compose file to server
  template:
    src: instance4-docker-compose.yaml.j2
    dest: '/home/ubuntu/docker-compose.yaml'
    owner: ubuntu
    group: ubuntu