---
# ********************* Common vars **************************************
availability_zone: melbourne-qh2-uom
project_working_directory: /home/ubuntu/COMP90024
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal
instance_image: 916cad7a-c545-48b2-b36c-d509ee63b3ce  #NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
instance_key_name: app_key
inventory_file: "{{ playbook_dir }}/inventory/hosts.ini"
# ********************* Volume ********************************************
volumes:
  - vol_name: volume_db1
    vol_size: 80
    device: /dev/vdb
    mountpoint: /data
  - vol_name: volume_db2
    vol_size: 80
    device: /dev/vdbcd
    mountpoint: /data
  - vol_name: volume_db3
    vol_size: 80
    device: /dev/vdb
    mountpoint: /data
  - vol_name: volume_db4
    vol_size: 20
    device: /dev/vdb
    mountpoint: /data

# ********************* Security group ************************************
security_groups:
  - name: ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: webserver
    description: "web server for HTTPs"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance1-security-group
    description: "security group for instance1 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance2-security-group
    description: "security group for instance2 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance3-security-group
    description: "security group for instance3 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance4-security-group
    description: "security group for instance4 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# ********************* Instance ****************************************
instances:
  - name: instance_1
    security_groups: default,http,ssh,webserver,instance1-security-group
    volume_ids: '{{ instance1_volumes|default([]) }}'
    volumes: ['volume_db1']
  - name: instance_2
    security_groups: default,http,ssh,webserver,instance2-security-group
    volume_ids: '{{ instance2_volumes|default([]) }}'
    volumes: ['volume_db2']
  - name: instance_3
    security_groups: default,http,ssh,webserver,instance3-security-group
    volume_ids: '{{ instance3_volumes|default([]) }}'
    volumes: ['volume_db3']
  - name: instance_4
    security_groups: default,http,ssh,webserver,instance4-security-group
    volume_ids: '{{ instance4_volumes|default([]) }}'
    volumes: ['volume_db4']

