---
- name: copy compose file to server
  become: yes
  template:
    src: instance1-docker-compose.yaml.j2
    dest: '/home/ubuntu/docker-compose.yaml'
    owner: ubuntu
    group: ubuntu

- name: copy nginx config to server
  become: yes
  template:
    src: web-nginx.conf.j2
    dest: '{{remote_working_directory}}/config/webserver_nginx/nginx.conf'
    owner: ubuntu
    group: ubuntu