---
# Set authorized key taken from file
- name: Set authorized key taken from file
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', '/Users/jade/Documents/unimelb/sm1 2021/CCC COMP90024 Cluster and Cloud Computing /Group Project/CCC-Group-Project/Ansible/app_key.pem.pub') }}"
