---
- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: setup-couchdb
    - role: setup-couchdb-cluster

- hosts: instance_1
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: git-pull-source
    - role: deploy-frontend
    - role: restart-docker-compose

- hosts: instance_2
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: git-pull-source
    - role: deploy-backend
    - role: restart-docker-compose

- hosts: instance_3
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: git-pull-source
    - role: deploy-nlp
    - role: restart-docker-compose

- hosts: instance_4
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: git-pull-source
    - role: deploy-ml-server
    - role: restart-docker-compose