- hosts: localhost
  vars_files:
    - host_vars/local_vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: show-images
    - role: create-volume
    - role: create-security-group
    - role: create-instance
