---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-key

- hosts: all
  vars_files:
    - host_vars/local_vars.yaml
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: set-proxy-enviroment
    - role: install-dependencies
    - role: setup-docker
    - role: git-clone-source-repository
    - role: mount-volumes